version: '3.8'

# ====================================== AIRFLOW ENVIRONMENT VARIABLES =======================================
x-environment: &airflow_environment
  - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://postgres:postgres@postgres:5432/airflow
  - AIRFLOW__CORE__STORE_DAG_CODE=True
  - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  - AIRFLOW__WEBSERVER__RBAC=False
x-airflow-image: &airflow_image apache/airflow:2.2.5-python3.9
# ====================================== /AIRFLOW ENVIRONMENT VARIABLES ======================================

services:
  django:
    build: .
    hostname: django
    container_name: Django
    ports:
      - "8000:8000"
    volumes:
      - .:/home/youdongknowme/
    command: bash -c "echo 'django START'
      && pip install psycopg2-binary --no-binary psycopg2-binary
      && cd /home/youdongknowme && python insert_data.py
      && cd /home/youdongknowme/main
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0:8000"
    depends_on:
      - postgreSQL
    tty: true

  #개발DB
  postgres:
    container_name: postgreSQL
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresql/init/:/docker-entrypoint-initdb.d/

  #Airflow
  init:
    image: *airflow_image
    depends_on:
      - postgres
    environment: *airflow_environment
    entrypoint: /bin/bash
    command: -c 'airflow db upgrade && sleep 5 && airflow users create --username gyehong --password qwe1234 --firstname gyehong --lastname lee --role Admin --email khong0819@gmail.co.kr'
  webserver:
    image: *airflow_image
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow:/opt/airflow
    environment: *airflow_environment
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: webserver
  scheduler:
    image: *airflow_image
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow:/opt/airflow
    environment: *airflow_environment
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: scheduler
